title: pwntricks-Blog
description: "A Jekyll Blog Theme For Hackers"
author:
  name: "hassan ali al-khafaji casp3r0x0"
  email: "hathhassan@gmail.com"
  url: "https://pwntricks.com/pwntricks-blog"

baseurl: /

source: .
destination: ./_site
permalink: /:title
paginate: 10
paginate_path: /page/:num/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
owner : "Casp3r0x0 hassan al-khafaji"
year : "2025"
google_analytics: "G-EV4ZXPN8D6"
